### PR TITLE
[MatterManipulator] Fix: Matter Manipulator does not move wireless hubs and wireless connectors correctly

### LINKED ISSUE #24269: The Matter Manipulator does not move wireless hubs and wireless connectors correctly
### Your GTNH Discord Username

OgRiCanX

### Your Pack Version

2.8.4 / Daily 455

### Your Server

private Server

### Java Version

Java 25

### Type of Server

Don't know

### Your Expectation

when moving 2 connected wireless connectors / hubs the connection between them should also be moved. 

### The Reality

when moving wireless connector and wireless hubs at the same time it does not move the wireless connector: 

Image

Image

### Your Proposal

move the connections correctly

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by Luca-Guettinger**
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/24269

### CODE REVIEW

File: src/main/java/com/recursive_pineapple/matter_manipulator/common/building/PendingMove.java [hunk 1]
```diff
@@ -204,6 +210,33 @@ public void onStopped() {
 
     }
 
+    private void fixWirelessLink(World world, Location dest) {
```
Comment (RecursivePineapple) [inline src/main/java/com/recursive_pineapple/matter_manipulator/common/building/PendingMove.java]: Can you make this a BlockMover instead? I'd like to keep custom code to a minimum, MM has enough of that. You should be able to copy StandardBlockMover for the most part, though you'll likely need to add a `PendingMove` parameter to `remove` and `place` so that you can keep the same `src...` logic.

Comment (Luca-Guettinger) [reply src/main/java/com/recursive_pineapple/matter_manipulator/common/building/PendingMove.java]: I changed it (locally, still need to test it). It feels like it would be better if the block movers were in separate files in their own package. This class seems kind of overloaded. should i extract the classes aswell?

Comment (RecursivePineapple) [reply src/main/java/com/recursive_pineapple/matter_manipulator/common/building/PendingMove.java]: Yeah, I just left them in here because they were fairly small. Feel free to pull them into their own files though.

Comment (Luca-Guettinger) [reply src/main/java/com/recursive_pineapple/matter_manipulator/common/building/PendingMove.java]: done

File: src/main/java/com/recursive_pineapple/matter_manipulator/common/building/movers/WirelessBlockMover.java [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+            lx >= pendingMove.getSrcMinX() && lx <= pendingMove.getSrcMaxX() &&
+                ly >= pendingMove.getSrcMinY() &&
+                ly <= pendingMove.getSrcMaxY() &&
+                lz >= pendingMove.getSrcMinZ() &&
+                lz <= pendingMove.getSrcMaxZ()
+        ) {
+            link.setInteger("x", lx + pendingMove.getMoveOffsetX());
+            link.setInteger("y", ly + pendingMove.getMoveOffsetY());
+            link.setInteger("z", lz + pendingMove.getMoveOffsetZ());
+            te.readFromNBT(nbt);
```
Comment (RecursivePineapple) [inline src/main/java/com/recursive_pineapple/matter_manipulator/common/building/movers/WirelessBlockMover.java]: Can you use `TileWireless.link()` and `TileWireless.doLink()` instead of doing NBT manipulation? If the data changes this'll break and we won't know.

Comment (Luca-Guettinger) [reply src/main/java/com/recursive_pineapple/matter_manipulator/common/building/movers/WirelessBlockMover.java]: done

**Review by RecursivePineapple — APPROVED** [review]
